// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_weather_app/test/auth_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:flutter_weather_app/src/helpers/connection.helper.dart' as _i3;
import 'package:flutter_weather_app/src/models/response.model.dart' as _i4;
import 'package:flutter_weather_app/src/repositories/sources/network/auth.service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

import 'auth_bloc_test.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAuthService_0 extends _i1.Fake implements _i2.AuthService {}

class _FakeConnectionHelper_1 extends _i1.Fake implements _i3.ConnectionHelper {
}

class _FakeResponseModel_2 extends _i1.Fake implements _i4.ResponseModel {}

/// A class which mocks [MockAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockAuthRepository extends _i1.Mock
    implements _i5.MockAuthRepository {
  MockMockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthService get api => (super.noSuchMethod(Invocation.getter(#api),
      returnValue: _FakeAuthService_0()) as _i2.AuthService);
  @override
  _i3.ConnectionHelper get connectionHelper =>
      (super.noSuchMethod(Invocation.getter(#connectionHelper),
          returnValue: _FakeConnectionHelper_1()) as _i3.ConnectionHelper);
  @override
  _i6.Future<_i4.ResponseModel> login(String? login, String? password) =>
      (super.noSuchMethod(Invocation.method(#login, [login, password]),
              returnValue:
                  Future<_i4.ResponseModel>.value(_FakeResponseModel_2()))
          as _i6.Future<_i4.ResponseModel>);
}

/// A class which mocks [MockAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockAuthService extends _i1.Mock implements _i5.MockAuthService {
  MockMockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ResponseModel> login(String? login, String? password) =>
      (super.noSuchMethod(Invocation.method(#login, [login, password]),
              returnValue:
                  Future<_i4.ResponseModel>.value(_FakeResponseModel_2()))
          as _i6.Future<_i4.ResponseModel>);
}
